import React, { useState } from 'react';
import { View, Text, ScrollView, Pressable, ActivityIndicator, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import RazorpayCheckout from 'react-native-razorpay';
import { useAuth } from '@/src/context/AuthContext';
import { paymentApi } from '@/src/api/paymentApi';

export default function SubscriptionScreen() {
  const router = useRouter();
  const { user, updateSessionUser } = useAuth();
  
  // Tracks which plan button is currently loading ('monthly' or 'yearly')
  const [loadingPlan, setLoadingPlan] = useState(null);

  const RAZORPAY_KEY_ID = 'rzp_test_wFLkgEpmzhmcWQ'; // Replace with your test/live key

//   const handleSubscribe = async (planId) => {
//     setLoadingPlan(planId);
//     try {
//       // 1. Create the Order on the Backend
//       const res = await paymentApi.createOrder(planId);
//       if (!res.success) throw new Error("Failed to create order");

//       // 2. Configure Razorpay UI Options
//       const options = {
//         description: `ShopOS Premium - ${planId === 'yearly' ? 'Annual' : 'Monthly'} Plan`,
//         image: 'https://your-logo-url.png', // Optional: Add your app logo URL
//         currency: 'INR',
//         key: RAZORPAY_KEY_ID,
//         order_id: res.order.id, // IMPORTANT: Pass the Order ID generated by your backend
//         name: 'ShopOS Premium',
//         prefill: {
//           email: user?.email || '',
//           contact: user?.phone_number || '',
//           name: user?.name || 'Shop Owner'
//         },
//         theme: { color: '#1f2617' }
//       };

//       // 3. Open Razorpay Native Checkout
//       RazorpayCheckout.open(options).then(async (data) => {
        
//         // 4. Verify the Payment Signature with the Backend
//         try {
//           const verifyRes = await paymentApi.verifyPayment({
//             razorpay_order_id: data.razorpay_order_id,
//             razorpay_payment_id: data.razorpay_payment_id,
//             razorpay_signature: data.razorpay_signature,
//             planId: planId
//           });

//           if (verifyRes.success) {
//             Alert.alert("Payment Successful", "Welcome to Premium!");
//             // Update local context so the UI unlocks premium features immediately
//             await updateUser({ 
//               isPremium: true, 
//               subscription: verifyRes.user.subscription 
//             });
//             router.back();
//           } else {
//             Alert.alert("Verification Failed", "Payment received but signature mismatch.");
//           }
//         } catch (verifyError) {
//           Alert.alert("Error", "Server error during verification. Please contact support.");
//         }

//       }).catch((error) => {
//         Alert.alert("Payment Cancelled", "Your transaction was not completed.");
//       });

//     } catch (error) {
//       Alert.alert("Error", "Could not initiate payment. Please try again.");
//     } finally {
//       setLoadingPlan(null);
//     }
//   };

    const handleSubscribe = async (planId) => {
  setLoadingPlan(planId);
  try {
    // 1. Create the Order on the Backend
    const res = await paymentApi.createOrder(planId);
    if (!res.success) throw new Error("Failed to create order");

    const options = {
      description: `PaperBill Premium - ${planId === 'yearly' ? 'Annual' : 'Monthly'} Plan`,
      image: 'https://your-logo-url.png', 
      currency: 'INR',
      key: RAZORPAY_KEY_ID,
      order_id: res.order.id, 
      name: 'PaperBill Premium',
      prefill: {
        email: user?.email || '',
        contact: user?.phone_number || '',
        name: user?.name || 'Shop Owner'
      },
      theme: { color: '#1f2617' }
    };

    // 2. Open Razorpay Native Checkout
    RazorpayCheckout.open(options).then(async (data) => {
      
      // --- ISOLATED API BLOCK ---
      let verifyRes;
      try {
        verifyRes = await paymentApi.verifyPayment({
          razorpay_order_id: data.razorpay_order_id,
          razorpay_payment_id: data.razorpay_payment_id,
          razorpay_signature: data.razorpay_signature,
          planId: planId
        });
      } catch (apiError) {
        // If the server times out, we catch it HERE specifically.
        Alert.alert("Notice", "Payment received, but verification took too long. Please refresh your profile.");
        return; 
      }

      // --- ISOLATED SUCCESS BLOCK ---
      if (verifyRes.success) {
        Alert.alert("Payment Successful", "Welcome to Premium!");
        
        try {
          // If updateUser crashes (e.g., storage error), it won't trigger a fake "Server Error" anymore
          if (updateSessionUser) {
            // We use the FULL updated user from the backend response,
            // not a partial object. This ensures all fields stay in sync.
            await updateSessionUser(verifyRes.user);
          }
        } catch (localError) {
          console.log("Local state update skipped. Profile screen will fetch fresh data.");
        }
        
        // Always go back to profile
        router.back();
      } else {
        Alert.alert("Verification Failed", "Payment received but signature mismatch.");
      }

    }).catch((error) => {
      // User closed the Razorpay modal
      Alert.alert("Payment Cancelled", "Your transaction was not completed.");
    });

  } catch (error) {
    Alert.alert("Error", "Could not initiate payment. Please try again.");
  } finally {
    setLoadingPlan(null);
  }
};

  return (
    <SafeAreaView className="flex-1 bg-bg">
      <View className="px-6 py-4 flex-row items-center justify-between">
        <Pressable onPress={() => router.back()} className="bg-card p-3 rounded-2xl active:opacity-50">
          <Feather name="arrow-left" size={20} color="#1f2617" />
        </Pressable>
        <Text className="text-primaryText text-xl font-black">Upgrade Shop</Text>
        <View className="w-10" />
      </View>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ padding: 24, paddingBottom: 100 }}>
        
        <View className="items-center mb-8 mt-2">
          <View className="bg-accent/20 w-24 h-24 rounded-full items-center justify-center mb-6">
            <MaterialCommunityIcons name="crown" size={48} color="#eab308" />
          </View>
          <Text className="text-primaryText text-4xl font-black text-center tracking-tighter">Premium</Text>
          <Text className="text-secondaryText font-medium text-center mt-2 leading-5">
            Unlock advanced analytics, unlimited staff accounts, and priority support.
          </Text>
        </View>

        {/* Features List */}
        <View className="bg-white p-6 rounded-[32px] border border-card shadow-sm mb-8">
          <FeatureRow text="Unlimited Invoices & Khata entries" />
          <FeatureRow text="Add up to 10 Staff Members" />
          <FeatureRow text="Advanced Profit & Loss Analytics" />
          <FeatureRow text="WhatsApp Invoice Sharing" />
          <FeatureRow text="Priority Cloud Backup" />
        </View>

        <Text className="text-secondaryText text-[10px] font-bold uppercase tracking-widest mb-4 ml-2 text-center">
          Choose Your Plan
        </Text>

        <View className="flex-row justify-between gap-4">
          {/* Monthly Plan Card */}
          <Pressable 
            disabled={loadingPlan !== null}
            onPress={() => handleSubscribe('monthly')}
            className="flex-1 bg-white p-5 rounded-[32px] border border-card shadow-sm items-center active:opacity-70"
          >
            <Text className="text-secondaryText font-bold text-[10px] uppercase tracking-widest mb-2">Monthly</Text>
            <Text className="text-primaryText font-black text-2xl mb-4">₹199</Text>
            <View className="bg-card w-full py-3 rounded-xl items-center">
              {loadingPlan === 'monthly' ? (
                <ActivityIndicator color="#1f2617" size="small" />
              ) : (
                <Text className="text-primaryText font-black text-xs uppercase tracking-widest">Select</Text>
              )}
            </View>
          </Pressable>

          {/* Yearly Plan Card (Highlighted) */}
          <Pressable 
            disabled={loadingPlan !== null}
            onPress={() => handleSubscribe('yearly')}
            className="flex-1 bg-primaryText p-5 rounded-[32px] items-center shadow-2xl relative active:opacity-70 border border-primaryText"
          >
            {/* Save Badge */}
            <View className="absolute -top-3 bg-red-500 px-3 py-1 rounded-full border border-white">
              <Text className="text-white font-black text-[9px] uppercase tracking-widest">Save 16%</Text>
            </View>
            
            <Text className="text-secondary font-bold text-[10px] uppercase tracking-widest mb-2 mt-2">Yearly</Text>
            <Text className="text-accent font-black text-2xl mb-4">₹1999</Text>
            <View className="bg-accent w-full py-3 rounded-xl items-center shadow-lg shadow-accent/20">
              {loadingPlan === 'yearly' ? (
                <ActivityIndicator color="#1f2617" size="small" />
              ) : (
                <Text className="text-[#1f2617] font-black text-xs uppercase tracking-widest">Select</Text>
              )}
            </View>
          </Pressable>
        </View>

        <Text className="text-secondaryText text-center text-[9px] mt-6 opacity-70">
          Secured by Razorpay • Cancel anytime
        </Text>

      </ScrollView>
    </SafeAreaView>
  );
}

const FeatureRow = ({ text }) => (
  <View className="flex-row items-center mb-4">
    <View className="bg-[#4ade80]/20 p-1.5 rounded-full mr-3">
      <Feather name="check" size={12} color="#4ade80" />
    </View>
    <Text className="text-primaryText font-bold text-sm flex-1">{text}</Text>
  </View>
);